CC=gcc
all:
	$(CC) -o setrtom setrtmon.c

	$(CC) -o cancelrtom cancelrtmon.c

	$(CC) -o printrtom printrtmon.c

clean: 
	sudo rm -f setrtmon 2> /dev/null
	sudo rm -f cancelrtmon 2> /dev/null
	sudo rm -f printrtmon 2> /dev/null	