CC=gcc
all:
	$(CC) -o setrtmon setrtmon.c

	$(CC) -o cancelrtmon cancelrtmon.c

	$(CC) -o printrtmon printrtmon.c

	$(CC) -o setrtmon_wait setrtmon_wait.c

clean: 
	sudo rm -f setrtmon 2> /dev/null
	sudo rm -f cancelrtmon 2> /dev/null
	sudo rm -f printrtmon 2> /dev/null	
	sudo rm -f setrtmon_wait 2> /dev/null